steps:
#step 1
- name: 'gcr.io/cloud-builders/docker' 
  entrypoint: 'bash'
  args: [
   '-c', 
   'docker pull us.gcr.io/image-347015/imagecaption || exit 0'
  ]
#step 2
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us.gcr.io/image-347015/imagecaption:latest','.']

# step3 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us.gcr.io/image-347015/imagecaption:latest']

#step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'rollout', 
   'restart', 
   'deployment/imagedevep'
   #'container-regression=us.gcr.io/regression-flask/container-regression:latest'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=image'